# Generated by Django 5.0.14 on 2025-11-27 16:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(editable=False, help_text='Auto-generated registration number', max_length=20, unique=True)),
                ('student_name', models.CharField(help_text='Full name of the student', max_length=200)),
                ('grade', models.IntegerField(help_text='Grade (2-12)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)])),
                ('school_name', models.CharField(help_text='Name of the school', max_length=200)),
                ('contact_number', models.CharField(help_text='Contact number', max_length=20)),
                ('email', models.EmailField(help_text='Email address', max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('free', 'Free Workshop')], default='pending', help_text='Payment status', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration',
                'verbose_name_plural': 'Registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Workshop name', max_length=200)),
                ('description', models.TextField(help_text='Workshop description')),
                ('workshop_date', models.CharField(help_text='Workshop date(s)', max_length=200)),
                ('venue', models.CharField(help_text='Workshop venue', max_length=200)),
                ('time', models.CharField(help_text='Workshop time', max_length=100)),
                ('duration', models.CharField(help_text='Workshop duration', max_length=100)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Workshop fee in BDT (0 for free workshops)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity', models.PositiveIntegerField(default=100, help_text='Maximum number of participants')),
                ('is_active', models.BooleanField(default=True, help_text='Whether workshop is accepting registrations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.CharField(blank=True, help_text='Workshop organizer/trainer', max_length=200)),
            ],
            options={
                'verbose_name': 'Workshop',
                'verbose_name_plural': 'Workshops',
                'ordering': ['workshop_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='SSLCommerz transaction ID', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='BDT', max_length=3)),
                ('payment_status', models.CharField(default='pending', max_length=50)),
                ('payment_method', models.CharField(choices=[('sslcommerz', 'SSLCommerz'), ('free', 'Free')], default='sslcommerz', max_length=20)),
                ('sslcommerz_data', models.JSONField(blank=True, help_text='Complete SSLCommerz response data', null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('registration', models.OneToOneField(help_text='Related registration', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='workshops.registration')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='workshop',
            field=models.ForeignKey(help_text='Workshop to register for', on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='workshops.workshop'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('email', 'workshop')},
        ),
    ]
