# Generated by Django 5.0.14 on 2025-12-01 01:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='School name', max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether school is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='registration',
            name='grade',
            field=models.IntegerField(choices=[(2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12')], help_text='Grade (2-12)', validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='school_name',
            field=models.CharField(blank=True, help_text='Name of the school', max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School of the student', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='workshops.school'),
        ),
    ]
